export type Book = {
  name: string;
  writer: string | null;
  publisher: string;
  series: string | null;
  pageCount: number;
  link: string;
};

export const books: Book[] = [
  {
    name: '100 Hadis',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 113,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-100-hadis-erol-ergun',
  },
  {
    name: 'Abdest Namaz',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-abdest-namaz-orhan-sezgin',
  },
  {
    name: 'Afacanlar Kitap-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-afacanlar-kitap-1',
  },
  {
    name: 'Afacanlar Kitap-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-afacanlar-kitap-2',
  },
  {
    name: 'Alican İle Arıcan - Hud Peygamberin Diyarında',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-alican-ile-arican-hud-peygamberin-diyarinda',
  },
  {
    name: 'Allah Kimleri Sever',
    writer: 'Abdülkadir NEŞELİ',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allah-kimleri-sever-abdulkadir-neseli',
  },
  {
    name: 'Topkuyruk ve Bıdık',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-1-topkuyruk-ve-bidik-erol-ergun',
  },
  {
    name: 'Tavşan Ailesi',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-2-tavsan-ve-ailesi-erol-ergun',
  },
  {
    name: 'Top Kuyrukların Cevizleri',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-3-top-kuyruklarin-cevizleri-erol-ergun',
  },
  {
    name: 'Şifalı İlaç',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-4-sifali-ilac-erol-ergun',
  },
  {
    name: 'Ormandaki Ağaçlar',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-6-ormandaki-agaclar-erol-ergun',
  },
  {
    name: 'Bebek Sincap',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-5-bebek-ve-sincap-erol-ergun',
  },
  {
    name: 'Kâinatın Hâkimi',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri Serisi',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-serisi-2-kainatin-hakimi-erol-ergun',
  },
  {
    name: 'Şevkatliler Şefkatlisi',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri Serisi',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-serisi-5-sefkatlilerin-sefkatlisi-erol-ergun',
  },
  {
    name: 'Kusursuz Yaratan',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri Serisi',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-serisi-6-kusursuz-yaratan-erol-ergun',
  },
  {
    name: 'Yüceler Yücesi',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri Serisi',
    pageCount: 81,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-serisi-7-yuceler-yucesi-erol-ergun',
  },
  {
    name: 'En Yüce Dost',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Allahın Güzel İsimleri Serisi',
    pageCount: 81,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-allahin-guzel-isimleri-serisi-8-en-yuce-dost-erol-ergun',
  },
  {
    name: 'Denizler Kralı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-1-denizler-krali',
  },
  {
    name: 'Bal Balina',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-10-bal-balina',
  },
  {
    name: 'Altın Kuş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-2-altin-kus',
  },
  {
    name: 'Tombul Fil',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-3-tombul-fil',
  },
  {
    name: 'Tembel Serçe',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-4-tembel-serce',
  },
  {
    name: 'Ressam Leylek',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-5-ressam-leylek',
  },
  {
    name: 'Guguk Mahkemede',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-6-guguk-mahkemede',
  },
  {
    name: 'Deniz Arısı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-7-deniz-arisi',
  },
  {
    name: 'Yarasa Miki',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-8-yarasa-miki',
  },
  {
    name: 'Şirin Kelebek',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Altın Kuş Masal Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-altin-kus-serisi-9-sirin-kelebek',
  },
  {
    name: 'Efendiler Efendisi Hazreti Muhammed (SAV)',
    writer: 'Rahime KAYA',
    publisher: 'Muştu Yayınları',
    series: 'Asr-ı Saadet Serisi',
    pageCount: 273,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-asr-i-saadet-serisi-1-efendiler-efendisi-hazreti-muhammed-sav-rahime-kaya',
  },
  {
    name: 'Yeryüzünün En Hayırlı Kadını Hz. Hatice',
    writer: 'Gülşen GAZEL',
    publisher: 'Muştu Yayınları',
    series: 'Asr-ı Saadet Serisi',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-asr-i-saadet-serisi-2-yeryuzunun-en-hayirli-kadini-hz-hatice-gulsen-gazel',
  },
  {
    name: 'Allah Resulünün Sadık Dostu Hz. Ebubekir',
    writer: 'Gülşen GAZEL',
    publisher: 'Muştu Yayınları',
    series: 'Asr-ı Saadet Serisi',
    pageCount: 113,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-asr-i-saadet-serisi-3-allah-resulunun-sadik-dostu-hz-ebubekir-gulsen-gazel',
  },
  {
    name: 'Hakkın ve Adaletin Timsali Hz. Ömer',
    writer: 'Tarık ÜNAL',
    publisher: 'Muştu Yayınları',
    series: 'Asr-ı Saadet Serisi',
    pageCount: 201,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-asr-i-saadet-serisi-4-hakkin-ve-adaletin-timsali-hz-omer-tarik-unal',
  },
  {
    name: 'İki Nur Sahibi Hazreti Osman',
    writer: 'Ferruh AKIN',
    publisher: 'Muştu Yayınları',
    series: 'Asr-ı Saadet Serisi',
    pageCount: 121,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-asr-i-saadet-serisi-5-iki-nur-sahibi-hazreti-osman-ferruh-akin',
  },
  {
    name: 'Leyleğin Ömrü',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-1-leylegin-omru',
  },
  {
    name: 'Kellik İlacı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-10-kellik-ilaci',
  },
  {
    name: 'Dikkatli Rehber',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-2-dikkatli-rehber',
  },
  {
    name: 'Dağcı Ayı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-3-dagci-ayi',
  },
  {
    name: 'Süslen Kuaför',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-4-suslen-kuafor',
  },
  {
    name: 'Ayının Saflığı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-5-ayinin-safligi',
  },
  {
    name: 'Güzellik Yarışması',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-6-guzellik-yarismasi',
  },
  {
    name: 'Eğri Oturuş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-7-egri-oturus',
  },
  {
    name: 'Başkan Karga',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-8-baskan-karga',
  },
  {
    name: 'Arının Öğüdü',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Atasözleriyle Fabllar Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-atasozleriyle-fabllar-serisi-9-arinin-ogudu',
  },
  {
    name: 'Gençlerle Nur Dersleri-1',
    writer: 'Bediüzzaman Said Nursi',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 177,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-genclerle-nur-dersleri-1',
  },
  {
    name: 'Gençlerle Nur Dersleri-2',
    writer: 'Bediüzzaman Said Nursi',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 177,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-genclerle-nur-dersleri-2',
  },
  {
    name: 'Nurlardan Seçmeler-1',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 193,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-1-asli-kaplan',
  },
  {
    name: 'Nurlardan Seçmeler-2',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 221,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-2-asli-kaplan',
  },
  {
    name: 'Nurlardan Seçmeler-3',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 215,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-3-asli-kaplan',
  },
  {
    name: 'Nurlardan Seçmeler-4',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 174,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-4-asli-kaplan',
  },
  {
    name: 'Nurlardan Seçmeler-5',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 193,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-5-asli-kaplan',
  },
  {
    name: 'Nurlardan Seçmeler-6',
    writer: 'Aslı KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Bediüzzaman Said Nursi',
    pageCount: 209,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzaman-said-nursi-nurlardan-secmeler-6-asli-kaplan',
  },
  {
    name: 'Bediüzzamanin Hayatı',
    writer: 'Emre EREN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 127,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-bediuzzamanin-hayati-emre-eren',
  },
  {
    name: 'Gülen Çocuklar - 5 Yaş - Etkinlik Kitabı-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Gülen Çocuklar',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-gulen-cocuklar-5-yas-etkinlik-kitabi-1',
  },
  {
    name: 'Gülen Çocuklar - 5 Yaş - Etkinlik Kitabı-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Gülen Çocuklar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-gulen-cocuklar-5-yas-etkinlik-kitabi-2',
  },
  {
    name: 'Gülen Çocuklar - 5 Yaş - Etkinlik Kitabı-3',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Gülen Çocuklar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-gulen-cocuklar-5-yas-etkinlik-kitabi-3',
  },
  {
    name: 'Gülen Çocuklar - 5 Yaş - Etkinlik Kitabı-4',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Gülen Çocuklar',
    pageCount: 23,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-gulen-cocuklar-5-yas-etkinlik-kitabi-4',
  },
  {
    name: 'Yumurcak-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-1',
  },
  {
    name: 'Yumurcak-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-2',
  },
  {
    name: 'Yumurcak-3',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-3',
  },
  {
    name: 'Yumurcak-4',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-4',
  },
  {
    name: 'Yumurcak-5',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-5',
  },
  {
    name: 'Yumurcak-6',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Benim Dinim Seti - Yumurcak',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-benim-dinim-seti-yumurcak-6',
  },
  {
    name: 'Beydaba - Kelile ve Dimne',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 343,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-beydaba-kelile-ve-dimne',
  },
  {
    name: 'Çanakkale Destanı-1 - Bir Hilal Uğruna',
    writer: 'Arif AKPINAR',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Destanı',
    pageCount: 105,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-destani-1-bir-hilal-ugruna-arif-akpinar',
  },
  {
    name: 'Çanakkale Destanı-2 - Cephede Bayram',
    writer: 'Arif AKPINAR',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Destanı',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-destani-2-cephede-bayram-arif-akpinar',
  },
  {
    name: 'Çanakkale Destanı-3 - Çanakkale İçinde',
    writer: 'Arif AKPINAR',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Destanı',
    pageCount: 113,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-destani-3-canakkale-icinde-arif-akpinar',
  },
  {
    name: 'Çanakkale Savaşı Hikayeleri-1 - Gönüllü Askerler',
    writer: 'Erdoğan TÜCAN',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Savaşı Hikayeleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-savasi-hikayeleri-1-gonullu-askerler-erdogan-tucan',
  },
  {
    name: 'Çanakkale Savaşı Hikayeleri-2 - Anzaklı Ömer',
    writer: 'Erdoğan TÜCAN',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Savaşı Hikayeleri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-savasi-hikayeleri-2-anzakli-omer-erdogan-tucan',
  },
  {
    name: 'Çanakkale Savaşı Hikayeleri-3 - Seyit Onbaşı',
    writer: 'Erdoğan TÜCAN',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Savaşı Hikayeleri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-savasi-hikayeleri-3-seyit-onbasi-erdogan-tucan',
  },
  {
    name: 'Çanakkale Savaşı Hikayeleri-4 - Nusret Mayın Gemisi',
    writer: 'Erdoğan TÜCAN',
    publisher: 'Muştu Yayınları',
    series: 'Çanakkale Savaşı Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-canakkale-savasi-hikayeleri-4-nusret-mayin-gemisi-erdogan-tucan',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-1 - Büyük Dostluk',
    writer: 'Halis ARPACI',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-1-buyuk-dostluk-halis-arpaci',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-2 - Mavi Mızıka',
    writer: 'Hümeyra COŞKUN',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 39,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-2-mavi-mizika-humeyra-coskun',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-3 - Son Pişmanlık',
    writer: 'Hümeyra COŞKUN',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-3-son-pismanlik-humeyra-coskun',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-4 - Kaybolan Kitap',
    writer: 'Hümeyra COŞKUN',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-4-kaybolan-kitap-humeyra-coskun',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-5 - Ormanda Yangın',
    writer: 'Halis ARPACI',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-5-ormanda-yangin-halis-arpaci',
  },
  {
    name: 'Çıtır İle Pıtır Serisi-6 - Kırmızı Mont',
    writer: 'Hümeyra COŞKUN',
    publisher: 'Muştu Yayınları',
    series: 'Çıtır İle Pıtır Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-citir-ile-pitir-serisi-6-kirmizi-mont-humeyra-coskun',
  },
  {
    name: 'Çizgilerle Sevgili Peygamberimizin Hayatı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 88,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cizgilerle-sevgili-peygamberimizin-hayati',
  },
  {
    name: 'Çocuklar İçin Görgü ve Nezaket Kuralları',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 151,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-gorgu-ve-nezaket-kurallari',
  },
  {
    name: 'Çocuklar İçin Kırk Hadis',
    writer: 'Adem GARİP',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-kirk-hadis-adem-garip',
  },
  {
    name: 'Çocuklar İçin Kurandan Kıssalar',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-kurandan-kissalar',
  },
  {
    name: 'Çocuklar İçin Kutlu Doğum Serisi - Gönüller Sultanı Efendimiz',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Kutlu Doğum Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-kutlu-dogum-serisi-gonuller-sultani-efendimiz',
  },
  {
    name: 'Çocuklar İçin Peygamberimizin Hayatı-1 - Kutlu Doğum',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Peygamberimizin Hayatı',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-peygamberimizin-hayati-1-kutlu-dogum',
  },
  {
    name: 'Çocuklar İçin Peygamberimizin Hayatı-2 - İslamiyetin Doğuşu',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Peygamberimizin Hayatı',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-peygamberimizin-hayati-2-islamiyetin-dogusu',
  },
  {
    name: 'Çocuklar İçin Peygamberimizin Hayatı-3 - Zor Yıllar',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Peygamberimizin Hayatı',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-peygamberimizin-hayati-3-zor-yillar',
  },
  {
    name: 'Çocuklar İçin Peygamberimizin Hayatı-4 - Mirac ve Hicret',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Peygamberimizin Hayatı',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-peygamberimizin-hayati-4-mirac-ve-hicret',
  },
  {
    name: 'Çocuklar İçin Peygamberimizin Hayatı-5 - Peygamberimizin Son Yılları',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Çocuklar İçin Peygamberimizin Hayatı',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-cocuklar-icin-peygamberimizin-hayati-5-peygamberimizin-son-yillari',
  },
  {
    name: 'Dinimi Seviyorum Seti - 10-11 Yaş Grubu-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 112,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-10-11-yas-grubu-1',
  },
  {
    name: 'Dinimi Seviyorum Seti - 10-11 Yaş Grubu-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 88,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-10-11-yas-grubu-2',
  },
  {
    name: 'Dinimi Seviyorum Seti - 10-11 Yaş Grubu-3',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 80,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-10-11-yas-grubu-3',
  },
  {
    name: 'Dinimi Seviyorum Seti - 12-14 Yaş Grubu-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 120,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-12-14-yas-grubu-1',
  },
  {
    name: 'Dinimi Seviyorum Seti - 12-14 Yaş Grubu-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 176,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-12-14-yas-grubu-2',
  },
  {
    name: 'Dinimi Seviyorum Seti - 5-6 Yaş Grubu',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dinimi Seviyorum Seti',
    pageCount: 144,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dinimi-seviyorum-seti-5-6-yas-grubu',
  },
  {
    name: 'Dört Arkadaş Serisi-1 - Fidan Yiyen Bozoğlak',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-1-fidan-yiyen-bozoglak',
  },
  {
    name: 'Dört Arkadaş Serisi-2 - Yaramaz Tay',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-2-yaramaz-tay',
  },
  {
    name: 'Dört Arkadaş Serisi-3 - Dikenli Yol',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-3-dikenli-yol',
  },
  {
    name: 'Dört Arkadaş Serisi-4 - Yürüyen Taş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-4-yuruyen-tas',
  },
  {
    name: 'Dört Arkadaş Serisi-5 - Hasta Ziyareti',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-5-hasta-ziyareti',
  },
  {
    name: 'Dört Arkadaş Serisi-6 - Tehlikeli Oyun',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Arkadaş Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-arkadas-serisi-6-tehlikeli-oyun',
  },
  {
    name: 'Dört Mevsim Dua Serisi - Sonbahar Duaları',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Mevsim Dua Serisi',
    pageCount: 184,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-mevsim-dua-serisi-sonbahar-dualari',
  },
  {
    name: 'Dört Mevsim Dua Serisi - Yaz Duaları-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Mevsim Dua Serisi',
    pageCount: 184,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-mevsim-dua-serisi-yaz-dualari-1',
  },
  {
    name: 'Dört Mevsim Dua Serisi - Yaz Duaları-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Dört Mevsim Dua Serisi',
    pageCount: 38,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dort-mevsim-dua-serisi-yaz-dualari-2',
  },
  {
    name: 'Dua ve Sure Ezber Kartları',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 111,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-dua-ve-sure-ezber-kartlari',
  },
  {
    name: 'Efendimizin Yüce Ahlakı',
    writer: 'Ferruh AKIN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 161,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-efendimizin-yuce-ahlaki-ferruh-akin',
  },
  {
    name: 'Fetih Kitapları - Fatih Sultan Mehmet',
    writer: 'Ekrem YEŞİLÇAYIR',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 159,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-fatih-sultan-mehmet-ekrem-yesilcayir',
  },
  {
    name: 'Fetih Kitapları - Fetihlerin Babası Sultan Alparslan',
    writer: 'Selahattin DİKMEN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-fetihlerin-babasi-sultan-alparslan-selahattin-dikmen',
  },
  {
    name: 'Fetih Kitapları - Kanuni Sultan Süleyman',
    writer: 'Ekrem YEŞİLÇAYIR',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-kanuni-sultan-suleyman-ekrem-yesilcayir',
  },
  {
    name: 'Fetih Kitapları - Kılıçarslanlar',
    writer: 'Selahattin DİKMEN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 161,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-kilicarslanlar-selahattin-dikmen',
  },
  {
    name: 'Fetih Kitapları - Mimar Sinan',
    writer: 'Halis ALÇIN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 177,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-mimar-sinan-halis-alcin',
  },
  {
    name: 'Fetih Kitapları - Orhan Gazi',
    writer: 'Ertuğrul Tarık DÖRDÜNCÜ',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-orhan-gazi-ertugrul-tarik-dorduncu',
  },
  {
    name: 'Fetih Kitapları - Osman Gazi',
    writer: 'Salih GÜLEN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 119,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-osman-gazi-salih-gulen',
  },
  {
    name: 'Fetih Kitapları - Süleyman Şah',
    writer: 'Selahattin DİKMEN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-suleyman-sah-selahattin-dikmen',
  },
  {
    name: 'Fetih Kitapları - Tiryaki Hasan Paşa',
    writer: 'Erdal AYÇİÇEK',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 144,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-tiryaki-hasan-pasa-erdal-aycicek',
  },
  {
    name: 'Fetih Kitapları - Yavuz Sultan Selim',
    writer: 'İsmail UZUN',
    publisher: 'Muştu Yayınları',
    series: 'Fetih Kitapları',
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fetih-kitaplari-yavuz-sultan-selim-ismail-uzun',
  },
  {
    name: 'Fotoğraflarla Abdest Namaz İlmihali',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-fotograflarla-abdest-namaz-ilmihali',
  },
  {
    name: 'Geç Olmadan',
    writer: 'Arif AKPINAR',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 151,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gec-olmadan-arif-akpinar',
  },
  {
    name: 'Geçmişten Günümüze Hikayeler-1 - Sinsi Plan',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Geçmişten Günümüze Hikayeler',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gecmisten-gunumuze-hikayeler-1-sinsi-plan-ruhi-demirel',
  },
  {
    name: 'Geçmişten Günümüze Hikayeler-1 - Susuz Mimar',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Geçmişten Günümüze Hikayeler',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gecmisten-gunumuze-hikayeler-1-susuz-mimar-ruhi-demirel',
  },
  {
    name: 'Genç İnsan ve Namaz',
    writer: 'Hasan DARCAN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 169,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-genc-insan-ve-namaz-hasan-darcan',
  },
  {
    name: 'Gencin Yol Rehberi-1',
    writer: 'A. Başak SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Gencin Yol Rehberi',
    pageCount: 268,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gencin-yol-rehberi-1-a-basak-sezgin',
  },
  {
    name: 'Gencin Yol Rehberi-2',
    writer: 'A. Başak SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Gencin Yol Rehberi',
    pageCount: 371,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gencin-yol-rehberi-2-a-basak-sezgin',
  },
  {
    name: 'Gençler İçin Seçme Hadisler',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 177,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gencler-icin-secme-hadisler',
  },
  {
    name: 'Gençlik İlmihali',
    writer: 'A. Başak SEZGİN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 161,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-genclik-ilmihali-a-basak-sezgin',
  },
  {
    name: 'Gökyüzü Serisi-1 - Yağmur Damlaları',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Gökyüzü Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gokyuzu-serisi-1-yagmur-damlalari',
  },
  {
    name: 'Gökyüzü Serisi-2 - Kuvvetli Rüzgar',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Gökyüzü Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gokyuzu-serisi-2-kuvvetli-ruzgar',
  },
  {
    name: 'Gökyüzü Serisi-3 - Kar Taneleri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Gökyüzü Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gokyuzu-serisi-3-kar-taneleri',
  },
  {
    name: 'Gönül Tahtımızın Eşsiz Sultanı Efendimiz (Muhtasar)',
    writer: 'Reşit HAYLAMAZ',
    publisher: 'Muştu Yayınları',
    series: 'Gönül Tahtımızın',
    pageCount: 617,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gonul-tahtimizin-essiz-sultani-efendimiz-muhtasar-resit-haylamaz',
  },
  {
    name: 'Gül Destesi',
    writer: 'Mehmet ERDOĞAN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 72,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-destesi-mehmet-erdogan',
  },
  {
    name: 'Gül Devri-1 - Hz. Muhammed',
    writer: 'Mustafa ERDOĞAN',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-1-hz-muhammed-mustafa-erdogan',
  },
  {
    name: 'Gül Devri-2 - Hz. Ebubekir',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-2-hz-ebubekir-ruhi-demirel',
  },
  {
    name: 'Gül Devri-3 - Hz. Ömer',
    writer: 'Zekeriya ULAŞLI',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-3-hz-omer-zekeriya-ulasli',
  },
  {
    name: 'Gül Devri-4 - Hz. Osman',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-4-hz-osman-ruhi-demirel',
  },
  {
    name: 'Gül Devri-5 - Hz. Ali',
    writer: 'Zekeriya ULAŞLI',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-5-hz-ali-zekeriya-ulasli',
  },
  {
    name: 'Gül Devri-6 - Hz. Hatice',
    writer: 'Mehmet BÜYÜKŞAHİN',
    publisher: 'Muştu Yayınları',
    series: 'Gül Devri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-devri-6-hz-hatice-mehmet-buyuksahin',
  },
  {
    name: 'Gül Kokulu Fabl Serisi-2 - Yürüyen Ağaç',
    writer: 'Mehmet ERDOĞAN',
    publisher: 'Muştu Yayınları',
    series: 'Gül Kokulu Fabl Serisi',
    pageCount: 112,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-kokulu-fabl-serisi-2-yuruyen-agac-mehmet-erdogan',
  },
  {
    name: 'Gül Manzaralı Pencereler',
    writer: 'Şaban ÖZÜDOĞRU',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 103,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gul-manzarali-pencereler-saban-ozudogru',
  },
  {
    name: 'Gülücük-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Gülücük',
    pageCount: 241,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gulucuk-1',
  },
  {
    name: 'Gülücük-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Gülücük',
    pageCount: 241,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gulucuk-2',
  },
  {
    name: 'Gülün Aklı',
    writer: 'A. Vahap AKTAŞ',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 154,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gulun-akli-a-vahap-aktas',
  },
  {
    name: 'Günebakan Çicekleri',
    writer: 'Zehra AYDÜZ',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gunebakan-cicekleri-zehra-ayduz',
  },
  {
    name: 'Gurbetteki Öğretmen M. Fethulllah Gülen',
    writer: 'Murat ALPTEKİN',
    publisher: 'Muştu Yayınları',
    series: 'Gurbetteki Öğretmen',
    pageCount: 167,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-gurbetteki-ogretmen-m-fethullah-gulen-murat-alptekin',
  },
  {
    name: 'Güzel Davranış Hikayeleri-1 - Anne Eli',
    writer: 'Osman KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-1-anne-eli-osman-kaplan',
  },
  {
    name: 'Güzel Davranış Hikayeleri-10 - Hediye',
    writer: 'Ahmet ÖZDEMİR',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 129,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-10-hediye-ahmet-ozdemir',
  },
  {
    name: 'Güzel Davranış Hikayeleri-2 - Mektup',
    writer: 'Erdoğan TÜCAN',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-2-mektup-erdogan-tucan',
  },
  {
    name: 'Güzel Davranış Hikayeleri-3 - Başaklardaki Bereket',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-3-basaklardaki-bereket-ruhi-demirel',
  },
  {
    name: 'Güzel Davranış Hikayeleri-4 - Acele Kan Aranıyor',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 81,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-4-acele-kan-araniyor-ruhi-demirel',
  },
  {
    name: 'Güzel Davranış Hikayeleri-5 - Karla Gelen Güzellik',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-5-karla-gelen-guzellik-ruhi-demirel',
  },
  {
    name: 'Güzel Davranış Hikayeleri-7 - Yardımsever Kardeşler',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-7-yardimsever-kardesler-ruhi-demirel',
  },
  {
    name: 'Güzel Davranış Hikayeleri-8 - Günün İyiliği',
    writer: 'Orhan BİLİR',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-8-gunun-iyiligi-orhan-bilir',
  },
  {
    name: 'Güzel Davranış Hikayeleri-9 - Sevmek Sevilmek',
    writer: 'Erol ERGÜN',
    publisher: 'Muştu Yayınları',
    series: 'Güzel Davranış Hikayeleri',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-davranis-hikayeleri-9-sevmek-sevilmek-erol-ergun',
  },
  {
    name: 'Güzel Dinim Serisi - 10 Yaş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 185,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-10-yas',
  },
  {
    name: 'Güzel Dinim Serisi - 11 Yaş ve Üzeri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 225,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-11-yas-ve-uzeri',
  },
  {
    name: 'Güzel Dinim Serisi - 5-6 Yaş Grubu',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinimi-serisi-5-6-yas-grubu',
  },
  {
    name: 'Güzel Dinim Serisi - 7 Yaş ve Üzeri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-7-yas-ve-uzeri',
  },
  {
    name: 'Güzel Dinim Serisi - 8 Yaş ve Üzeri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 161,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-8-yas-ve-uzeri',
  },
  {
    name: 'Güzel Dinim Serisi - 9 Yaş ve Üzeri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 208,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-9-yas-ve-uzeri',
  },
  {
    name: 'Güzel Dinim Serisi-1 - Anahtar',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Güzel Dinim Serisi',
    pageCount: 64,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-guzel-dinim-serisi-1-anahtar',
  },
  {
    name: 'Hadis Hikayeleri-1 - Bir Küp Altın',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hadis Hikayeleri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hadis-hikayeleri-1-bir-kup-altin',
  },
  {
    name: 'Hadis Hikayeleri-1 - Şaşırtan Sevinç',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hadis Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hadis-hikayeleri-1-sasirtan-sevinc',
  },
  {
    name: 'Harika Hayvanlar',
    writer: 'Yasemin DEMİRCİ',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 113,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-harika-hayvanlar-yasemin-demirci',
  },
  {
    name: 'Hünerli Eller Serisi-1 - Faaliyet',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hünerli Eller Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hunerli-eller-serisi-1-faaliyet',
  },
  {
    name: 'Hünerli Eller Serisi-2 - Yemek',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hünerli Eller Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hunerli-eller-serisi-2-yemek',
  },
  {
    name: 'Hünerli Eller Serisi-3 - Boyama ve Kavram',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hünerli Eller Serisi',
    pageCount: 25,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hunerli-eller-serisi-3-boyama-ve-kavram',
  },
  {
    name: 'Hünerli Hayvanlar - Hayatın İlham Kaynağı',
    writer: 'Abdullah ARAZ',
    publisher: 'Muştu Yayınları',
    series: 'Hünerli Hayvanlar',
    pageCount: 245,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hunerli-hayvanlar-hayatin-ilham-kaynagi-abdullah-araz',
  },
  {
    name: 'Hünerli Hayvanlar Serisi - Kocaman Gövdeliler',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Hünerli Hayvanlar Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-hunerli-hayvanlar-serisi-kocaman-govdeliler',
  },
  {
    name: 'İbadet Serisi-1 - Hadis ve Hadiselerin Diliyle - Namaz',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'İbadet Serisi',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ibadet-serisi-1-hadis-ve-hadislerin-diliyle-namaz',
  },
  {
    name: 'İbadet Serisi-2 - Hadis ve Hadiselerin Diliyle - Oruç',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'İbadet Serisi',
    pageCount: 129,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ibadet-serisi-2-hadis-ve-hadislerin-diliyle-oruc',
  },
  {
    name: 'İbadet Serisi-3 - Hadis ve Hadiselerin Diliyle - Zekat',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'İbadet Serisi',
    pageCount: 169,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ibadet-serisi-3-hadis-ve-hadislerin-diliyle-zekat',
  },
  {
    name: 'İbadet Serisi-4 - Hadis ve Hadiselerin Diliyle - Hacc',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'İbadet Serisi',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ibadet-serisi-4-hadis-ve-hadislerin-diliyle-hacc',
  },
  {
    name: 'İbretli Masallar Serisi-1 - Ulu Ağacın Tılsımı',
    writer: 'Rabia KANDIRA',
    publisher: 'Muştu Yayınları',
    series: 'İbretli Masallar Serisi',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ibretli-masallar-serisi-1-ulu-agacin-tilsimi-rabia-kandira',
  },
  {
    name: 'İlber Hocayla Topkapı Sarayı Gezi Rehberi',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilber-hocayla-topkapi-sarayi-gezi-rehberi',
  },
  {
    name: 'İlk Öykülerim Serisi-1 - Yeşil Tespih',
    writer: 'Rabia KANDIRA',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-1-yesil-tesbih-rabia-kandira',
  },
  {
    name: 'İlk Öykülerim Serisi-10 - Kaybolan Top',
    writer: 'H. İbrahim ÇAYIRLI',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-10-kaybolan-top-h-ibrahim-cayirli',
  },
  {
    name: 'İlk Öykülerim Serisi-2 - Minik Kedi',
    writer: 'Rabia KANDIRA',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-2-minik-kedi-rabia-kandira',
  },
  {
    name: 'İlk Öykülerim Serisi-5 - Yarım Elma',
    writer: 'Osman KAPLAN',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-5-yarim-elma-osman-kaplan',
  },
  {
    name: 'İlk Öykülerim Serisi-6 - Hazine Peşinde',
    writer: 'Şafak DEMİR',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-6-hazine-pesinde-safak-demir',
  },
  {
    name: 'İlk Öykülerim Serisi-7 - Evimizin Forveti',
    writer: 'Şafak DEMİR',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-7-evimizin-forveti-safak-demir',
  },
  {
    name: 'İlk Öykülerim Serisi-8 - Babamın Sol Ayağı',
    writer: 'H. İbrahim ÇAYIRLI',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-8-babamin-sol-ayagi-h-ibrahim-cayirli',
  },
  {
    name: 'İlk Öykülerim Serisi-9 - Şeftali Ağacı',
    writer: 'Aysel ERTAN',
    publisher: 'Muştu Yayınları',
    series: 'İlk Öykülerim Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-ilk-oykulerim-serisi-9-seftali-agaci-aysel-ertan',
  },
  {
    name: 'İman Bahçesi Serisi - Rüzgar Duası',
    writer: 'Mesut KUTLU',
    publisher: 'Muştu Yayınları',
    series: 'İman Bahçesi Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-bahcesi-serisi-ruzgar-duasi-mesut-kutlu',
  },
  {
    name: "İman Serisi-1 - Allah'a İnanıyorum",
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-1-allaha-inaniyorum-osman-ural',
  },
  {
    name: 'İman Serisi-2 - Meleklere İnanıyorum',
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 129,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-2-meleklere-inaniyorum-osman-ural',
  },
  {
    name: 'İman Serisi-3 - Kitaplara İnanıyorum',
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-3-kitaplara-inaniyorum-osman-ural',
  },
  {
    name: 'İman Serisi-4 - Peygamberlere İnanıyorum',
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-4-peygamberlere-inaniyorum-osman-ural',
  },
  {
    name: 'İman Serisi-5 - Ahiret Gününe İnanıyorum',
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 145,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-5-ahiret-gunune-inaniyorum-osman-ural',
  },
  {
    name: 'İman Serisi-6 - Kaza ve Kadere İnanıyorum',
    writer: 'Osman URAL',
    publisher: 'Muştu Yayınları',
    series: 'İman Serisi',
    pageCount: 105,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-iman-serisi-6-kaza-ve-kadere-inaniyorum-osman-ural',
  },
  {
    name: 'İnanc Serisi-3 - Akkuyruk',
    writer: 'Mesut KUTLU',
    publisher: 'Muştu Yayınları',
    series: 'İnanc Serisi',
    pageCount: 41,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-inanc-serisi-3-akkuyruk-mesut-kutlu',
  },
  {
    name: 'Kahramanlık Hikayeleri-10 - Baskın',
    writer: 'Ersin TERES',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-10-baskin-ersin-teres',
  },
  {
    name: 'Kahramanlık Hikayeleri-2 - Şehit Şerife Bacı',
    writer: 'Mehmet SAYAN',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 81,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-2-sehit-serife-baci-mehmet-sayan',
  },
  {
    name: 'Kahramanlık Hikayeleri-3 - Küpeli Asker',
    writer: 'Fazıl YAZICI',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-3-kupeli-asker-fazil-yazici',
  },
  {
    name: 'Kahramanlık Hikayeleri-4 - Küçük Gazi',
    writer: 'Fazıl YAZICI',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-4-kucuk-gazi-fazil-yazici',
  },
  {
    name: 'Kahramanlık Hikayeleri-5 - Bu Millet Ölmez',
    writer: 'Fazıl YAZICI',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-5-bu-millet-olmez-fazil-yazici',
  },
  {
    name: 'Kahramanlık Hikayeleri-6 - Direniş Günleri',
    writer: 'Fazıl YAZICI',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-6-direnis-gunleri-fazil-yazici',
  },
  {
    name: 'Kahramanlık Hikayeleri-7 - Posta Güvercini',
    writer: 'Fazıl YAZICI',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 81,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-7-posta-guvercini-fazil-yazici',
  },
  {
    name: 'Kahramanlık Hikayeleri-8 - Antep Semalarında Bir Şahin',
    writer: 'Ersin TERES',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-8-antep-semalarinda-bir-sahin-ersin-teres',
  },
  {
    name: 'Kahramanlık Hikayeleri-9 - Gönderden İnmeyen Bayrak',
    writer: 'Ersin TERES',
    publisher: 'Muştu Yayınları',
    series: 'Kahramanlık Hikayeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kahramanlik-hikayeleri-9-gonderden-inmeyen-bayrak-ersin-teres',
  },
  {
    name: 'Keçeli Ali Serisi-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Keçeli Ali Serisi',
    pageCount: 16,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-keceli-ali-serisi-1',
  },
  {
    name: 'Keçeli Ali Serisi-3',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Keçeli Ali Serisi',
    pageCount: 16,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-keceli-ali-serisi-3',
  },
  {
    name: 'Kelime Haznem',
    writer: 'Betül ERTEKİN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kelime-haznem-betul-ertekin',
  },
  {
    name: 'Kıssalardan Dersler-1 - Gömülü Para',
    writer: 'Hasan KOCA',
    publisher: 'Muştu Yayınları',
    series: 'Kıssalardan Dersler',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kissalardan-dersler-1-gomulu-para-hasan-koca',
  },
  {
    name: 'Kıssalardan Dersler-2',
    writer: 'Zekeriya ULAŞLI',
    publisher: 'Muştu Yayınları',
    series: 'Kıssalardan Dersler',
    pageCount: 176,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kissalardan-dersler-2-zekeriya-ulasli',
  },
  {
    name: 'Küçük Selim Serisi-1 - Kırmızı Araba',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 4,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-1-kirmizi-araba',
  },
  {
    name: 'Küçük Selim Serisi-2 - Gece Yemeği',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 3,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-2-gece-yemegi',
  },
  {
    name: 'Küçük Selim Serisi-3 - Islak Bilyeler',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 3,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-3-islak-bilyeler',
  },
  {
    name: 'Küçük Selim Serisi-4 - Hediye Paketi',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 3,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-4-hediye-paketi',
  },
  {
    name: 'Küçük Selim Serisi-5 - Büyük Kitap',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 3,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-5-buyuk-kitap',
  },
  {
    name: 'Küçük Selim Serisi-6 - Kuzu Arkadaşım',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 3,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selim-serisi-6-kuzu-arkadasim',
  },
  {
    name: 'Küçük Selimin Maceraları Tamamı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Küçük Selim Serisi',
    pageCount: 48,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kucuk-selimin-maceralari-tamami',
  },
  {
    name: 'Kültür Kitapları Serisi - Binbir Gece Masalları-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kültür Kitapları Serisi',
    pageCount: 155,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kultur-kitaplari-serisi-binbir-gece-masallari-1',
  },
  {
    name: 'Kültür Kitapları Serisi - Binbir Gece Masalları-3',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kültür Kitapları Serisi',
    pageCount: 169,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kultur-kitaplari-serisi-binbir-gece-masallari-3',
  },
  {
    name: 'Kültür Kitapları Serisi - Dede Korkut Hikayeleri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kültür Kitapları Serisi',
    pageCount: 141,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kultur-kitaplari-serisi-dede-korkut-hikayeleri',
  },
  {
    name: 'Kültür Kitapları Serisi - Hayy',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kültür Kitapları Serisi',
    pageCount: 71,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kultur-kitaplari-serisi-hayy',
  },
  {
    name: 'Kur-an Elifbası İlmihali',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 136,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kur-an-elifbasi-ilmihalli',
  },
  {
    name: 'Kuran Öğreniyorum Seti-1 - Kuran Harflerini Öğreniyorum',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kuran Öğreniyorum Seti',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kuran-ogreniyorum-seti-1-kuran-harflerini-ogreniyorum',
  },
  {
    name: 'Kuran Öğreniyorum Seti-2 - Harekeleri Öğreniyorum',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kuran Öğreniyorum Seti',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kuran-ogreniyorum-seti-2-harekeleri-ogreniyorum',
  },
  {
    name: 'Kuran Öğreniyorum Seti-3 - Dua ve Sureleri Öğreniyorum',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kuran Öğreniyorum Seti',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kuran-ogreniyorum-seti-3-dua-ve-sureleri-ogreniyorum',
  },
  {
    name: 'Kuran Öğretim Seti - Okul Dönemi Öğrencilerine',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kuran Öğretim Seti',
    pageCount: 113,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kuran-ogretim-seti-okul-donemi-ogrencilerine',
  },
  {
    name: 'Kurtulus Savaşı Kahramanlık Öyküleri-1 - Patlamayan Dinamitler',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Kurtulus Savaşı Kahramanlık Öyküleri',
    pageCount: 73,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-kurtulus-savasi-kahramanlik-oykuleri-1-patlamayan-dinamitleri',
  },
  {
    name: 'M. Fethullah Gülen - Gençlere Pırlanta Ölçüler-1',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'M. Fethullah Gülen - Gençlere Pırlanta Ölçüler',
    pageCount: 273,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-m-fethullah-gulen-genclerle-pirlanta-olculer-1',
  },
  {
    name: 'M. Fethullah Gülen - Gençlere Pırlanta Ölçüler-2',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'M. Fethullah Gülen - Gençlere Pırlanta Ölçüler',
    pageCount: 305,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-m-fethullah-gulen-genclerle-pirlanta-olculer-2',
  },
  {
    name: 'Manzum Fabller-1 - Bir Demet Masal',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Manzum Fabller',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-manzum-fabller-1-bir-demet-masal',
  },
  {
    name: 'Meraklı Adem Serisi-5 - Sultanın Sarayı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Meraklı Adem Serisi',
    pageCount: 48,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-merakli-adem-serisi-5-sultanin-sarayi',
  },
  {
    name: 'Minik Kalbim - Boyama ve Etkinlik Kitabı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-minik-kalbim-boyama-ve-etkinlik-kitabi',
  },
  {
    name: 'Minik Kalbim-2 - Maket Kitabı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Minik Kalbim',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-minik-kalbim-2-maket-kitabi',
  },
  {
    name: 'Minik Kalbim-2 - Peygamberimizi Çok Seviyorum',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Minik Kalbim',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-minik-kalbim-2-peygamberimizi-cok-seviyorum',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-1 - Üç Kardeş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-1-uc-kardes',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-2 - Kandil Kartı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-2-kandil-karti',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-3 - Hayırlı Dua',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-3-hayirli-dua',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-4 - Güzel Kitap',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-4-guzel-kitap',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-5 - Süslü Kart',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-5-suslu-kart',
  },
  {
    name: 'Mübarek Gün ve Geceler Serisi-6 - Köydeki Cami',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Mübarek Gün ve Geceler Serisi',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-mubarek-gun-ve-geceler-serisi-6-koydeki-cami',
  },
  {
    name: 'Pamuk Dede İle Şeker Nine - Penceredeki Güvercinler',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Pamuk Dede İle Şeker Nine',
    pageCount: 17,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-pamuk-dede-ile-seker-nine-penceredeki-guvercinler',
  },
  {
    name: 'Peygamber Dostları Serisi-3 - Bir Tas Çorba',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Dostları Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-dostlari-serisi-3-bir-tas-corba',
  },
  {
    name: 'Peygamber Dostları Serisi-4 - Gerçek Müşteri',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Dostları Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-dostlari-serisi-3-gercek-musteri',
  },
  {
    name: 'Peygamber Dostları Serisi-5 - Kırılan Kalp',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Dostları Serisi',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-dostlari-serisi-5-kirilan-kalp',
  },
  {
    name: 'Peygamber Dostları Serisi-6 - Yol Arkadaş',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Dostları Serisi',
    pageCount: 57,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-dostlari-serisi-6-yol-arkadasi',
  },
  {
    name: 'Peygamber Dostları Serisi-7 - Sevinç Yılı',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Dostları Serisi',
    pageCount: 65,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-dostlari-serisi-7-sevinc-yili',
  },
  {
    name: 'Peygamber Efendimizden Kıssalar',
    writer: 'Mehmet KÜÇÜK',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 185,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizden-kissalar-mehmet-kucuk',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-1 - Konuşan Kurt',
    writer: 'İdris ÖZDEMİR',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-1-konusan-kurt-idris-ozdemir',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-2 - Ağlayan Kütük',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-2-aglayan-kutuk-ruhi-demirel',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-3 - Zikreden Taşlar',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-3-zikreden-taslar-ruhi-demirel',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-4 - Gökten İnen Su',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-4-gokten-inen-su-ruhi-demirel',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-5 - Bereketlenen Yemek',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-5-bereketlenen-yemek-ruhi-demirel',
  },
  {
    name: 'Peygamber Efendimizin Mucizeleri-6 - Işık Saçan Asa',
    writer: 'Ruhi DEMİREL',
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Mucizeleri',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-mucizeleri-6-isik-sacan-asa-ruhi-demirel',
  },
  {
    name: 'Peygamber Efendimizin Sünnetleri - Gül Gibi Hayat',
    writer: null,
    publisher: 'Muştu Yayınları',
    series: 'Peygamber Efendimizin Sünnetleri',
    pageCount: 105,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-efendimizin-sunnetleri-gul-gibi-hayat',
  },
  {
    name: 'Peygamber Sevdalıları',
    writer: 'Arif AKPINAR',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 137,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamber-sevdalilari-arif-akpinar',
  },
  {
    name: 'Peygamberimizden Hatıralar-1 Yavru Deve',
    writer: 'Ahmet TÜRKMENOĞLU',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-1-yavru-deve-ahmet-turkmenoglu',
  },
  {
    name: 'Peygamberimizden Hatıralar-10 Yenilmeyen Pehlivan',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-10-yenilenmeyen-pehlivan-orhan-sezgin',
  },
  {
    name: 'Peygamberimizden Hatıralar-2 Yavru Kuşlar',
    writer: 'Ahmet TÜRKMENOĞLU',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-2-yavru-kuslar-ahmet-turkmenoglu',
  },
  {
    name: 'Peygamberimizden Hatıralar-3 Kır Çiçekleri',
    writer: 'Ahmet TÜRKMENOĞLU',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-3-kir-cicekleri-ahmet-turkmenoglu',
  },
  {
    name: 'Peygamberimizden Hatıralar-4 Küçük Serçe',
    writer: 'Ahmet TÜRKMENOĞLU',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 49,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-4-kucuk-serce-ahmet-turkmenoglu',
  },
  {
    name: 'Peygamberimizden Hatıralar-5 Komşunun Ağacı',
    writer: 'A. Başak SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-5-komsunun-agaci-a-basak-sezgin',
  },
  {
    name: 'Peygamberimizden Hatıralar-6 Küçük Çoban',
    writer: 'A. Başak SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-6-kucuk-coban-a-basak-sezgin',
  },
  {
    name: 'Peygamberimizden Hatıralar-7 Bereketlenen Hurmalar',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-7-bereketlenen-hurmalar-orhan-sezgin',
  },
  {
    name: 'Peygamberimizden Hatıralar-8 Bahiranın Gördükleri',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-8-bahiranin-gordukleri-orhan-sezgin',
  },
  {
    name: 'Peygamberimizden Hatıralar-9 Efendimizin Hicreti',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Peygamberimizden Hatıralar',
    pageCount: 33,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberlerimizden-hatiralar-9-efendimizin-hicreti-orhan-sezgin',
  },
  {
    name: 'Peygamberler Tarihi',
    writer: 'Cemalettin YAZICI',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 305,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-peygamberler-tarihi-cemalettin-yazici',
  },
  {
    name: 'Rehberim Sevgili Peygamberim (SAV)',
    writer: 'Yusuf ÖZARSLAN',
    publisher: 'Muştu Yayınları',
    series: null,
    pageCount: 265,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-rehberim-sevgili-peygamberim-sav-yusuf-ozarslan',
  },
  {
    name: 'Risale Hikayeleri Serisi - Gökkuşağının Ardındaki Ülke',
    writer: 'Nur PAKDEMİRLİ',
    publisher: 'Muştu Yayınları',
    series: 'Risale Hikayeleri Serisi',
    pageCount: 97,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-risale-hikayeleri-serisi-gokkusaginin-ardindaki-ulke-nur-pakdemirli',
  },
  {
    name: 'Risale Hikayeleri Serisi - Hayat Meydanı',
    writer: 'Orhan SEZGİN',
    publisher: 'Muştu Yayınları',
    series: 'Risale Hikayeleri Serisi',
    pageCount: 78,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-risale-hikayeleri-serisi-hayat-meydani-orhan-sezgin',
  },
  {
    name: 'Risale Hikayeleri Serisi - Yol Ayrımı',
    writer: 'Nur PAKDEMİRLİ',
    publisher: 'Muştu Yayınları',
    series: 'Risale Hikayeleri Serisi',
    pageCount: 89,
    link: 'https://www.hizmetsource.com/book/mustu-yayinlari-risale-hikayeleri-serisi-yol-ayrimi-nur-pakdemirli',
  },
];
